language: python
python:
    - 3.5
sudo: false
env:
  global:
    secure: Q+zj/DvhiTwO3eaFlB3qejX7fV2OKi6w6wehPP66rEYIkzQKuFq3F08cdqd39En0qrLr4z6X4fXVRjuhIXrbk1x5CRdpcG78QxxdFyyFD4qeQLG8z+Fkvu09uFaQxuwbBDfm0uKeQAuxc7m51kldDnqHbIm2L6pSWNePQCJvbYEcLe+y57rDARjkyU6TTPbC9AUrcdVyQ/H1ZY1cTbcBTGuJK5hYM8s4EAf1iW5J+amhYxPWOHRREsiggYq65Vv2ehx+QExrtoG4+hUJlTUF4I1NubhtSnykUO0WhekDF+R+/KH6pfPATKpx9ZC/JvETtpp05FImRQRnke1ZLLnjMuJisLDkLAfeD/nxC4bduDWx6dt4BsIP2/pH0/U5aPYxdLOcWrMHjP6z9iz6IzvgiuZCQbMwa6oYLUdThFGIqLjTlwX2/7yulOSJqjGFftK6cioxmD16DFVXfcbevMZfXqMkymCOLgPwMcWxQXcXY6K7KrAmSl9XYCHWxOYiLZ5555+CXoC6U7PPJ5TunxbnlZ47n5vMHbkcNYKPM4wGwTb3AJI+vxIfEM0qkqzSGx/nN5vA/xtzoXcbUzexpXGY9ZJY4rM4g1TAhWC0uWH3mCeddVNishPqMRFMtJmm4nQqL+qQxFbomazhSBnhafyTTyyRu0S+2q4ra8in5Q2PaiE=
install:
    - "pip install -r requirements.txt"
script:
    - "true"
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
